version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: community-mysql
    ports:
      - '3366:3306'
    environment:
      MYSQL_ROOT_PASSWORD: community_root
      MYSQL_DATABASE: community
      MYSQL_USER: community_user
      MYSQL_PASSWORD: community_password
    volumes:
      - ./mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --character-set-client-handshake=false
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
