version: '3.8'

services:
  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: community
      MYSQL_USER: community_user
      MYSQL_PASSWORD: community_password
    volumes:
      - ./database/mysql/master/init.sql:/docker-entrypoint-initdb.d/init.sql
      - master-data:/var/lib/mysql
    command:
      - --server-id=1
      - --log-bin=mysql-bin
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    networks:
      - mysql-net

  mysql-slave:
    image: mysql:8.0
    container_name: mysql-slave
    depends_on:
      - mysql-master
    ports:
      - '3308:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: community
      MYSQL_USER: community_user
      MYSQL_PASSWORD: community_password
    volumes:
      - ./database/mysql/slave/init.sql:/docker-entrypoint-initdb.d/init.sql
      - slave-data:/var/lib/mysql
    command:
      - --server-id=2
      - --relay-log=relay-log
      - --read-only=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    networks:
      - mysql-net

volumes:
  master-data:
  slave-data:

networks:
  mysql-net:
